<?xml version="1.0" encoding="utf-8"?><Database Name="HieuDesigner" Class="DBContextsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-AJ7R3H3\SQLEXPRESS;Initial Catalog=HieuDesigner;User ID=sa" SettingsObjectName="Models.Properties.Settings" SettingsPropertyName="HieuDesignerConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Baner" Member="Baners">
    <Type Name="Baner">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="location" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BaoGia" Member="BaoGias">
    <Type Name="BaoGia">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HotenKH" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="itemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Item_BaoGia" Member="Item" ThisKey="itemID" OtherKey="Id" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="DanhMuc_DanhMucCon" Member="DanhMucCons" ThisKey="Id" OtherKey="ID_DanhMucCha" Type="DanhMucCon" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucCon" Member="DanhMucCons">
    <Type Name="DanhMucCon">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ID_DanhMucCha" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DanhMucCon_Item" Member="Items" ThisKey="Id" OtherKey="ID_DanhMucCon" Type="Item" />
      <Association Name="DanhMuc_DanhMucCon" Member="DanhMuc" ThisKey="ID_DanhMucCha" OtherKey="Id" Type="DanhMuc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tile" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ID_DanhMucCon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Item_BaoGia" Member="BaoGias" ThisKey="Id" OtherKey="itemID" Type="BaoGia" />
      <Association Name="DanhMucCon_Item" Member="DanhMucCon" ThisKey="ID_DanhMucCon" OtherKey="Id" Type="DanhMucCon" IsForeignKey="true" />
    </Type>
  </Table>
</Database>